<?php
/* Generated by Juju
 */
$conf['title'] = 'Dokuwiki';
$conf['tagline'] = 'deployed by Juju';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['showuseras'] = 'username';
$conf['youarehere'] = 1;
$conf['gzip_output'] = 1;
$conf['sitemap'] = 1;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;