options:
  app_path:
    type: string
    default: "/srv/app"
    description: "Where Dokuwiki will be installed"
  admin_user:
    type: string
    default: admin
    description: "Admin username (default: admin)"
  admin_password:
    type: string
    default: "5f4dcc3b5aa765d61d8327deb882cf99"
    description: "Admin password md5 hash format (default password: password)"
  admin_name:
    type: string
    default: "The Admin"
    description: Admin name
  admin_email:
    type: string
    default: "admin@example.com"
    description: Admin email
