#!/usr/bin/env ruby

require "charmkit"

if ARGV.length > 1
  puts "To many arguments, should be one of 'install, config-changed, start, stop, upgrade-charm'"
  exit 1
end

hook_name = ARGV.pop

if File.exists?("Charmkitfile")
  load "Charmkitfile"
else
  puts "Could not find Charmkitfile"
  exit 1
end
